//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication4.ServiceSF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.expressservice.integration.sf.com/", ConfigurationName="ServiceSF.IService")]
    public interface IService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WindowsFormsApplication4.ServiceSF.sfexpressServiceResponse sfexpressService(WindowsFormsApplication4.ServiceSF.sfexpressService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication4.ServiceSF.sfexpressServiceResponse> sfexpressServiceAsync(WindowsFormsApplication4.ServiceSF.sfexpressService request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelResponse expressServiceForRouteLabel(WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelResponse> expressServiceForRouteLabelAsync(WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabel request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sfexpressService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sfexpressService", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public WindowsFormsApplication4.ServiceSF.sfexpressServiceBody Body;
        
        public sfexpressService() {
        }
        
        public sfexpressService(WindowsFormsApplication4.ServiceSF.sfexpressServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sfexpressServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public sfexpressServiceBody() {
        }
        
        public sfexpressServiceBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sfexpressServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sfexpressServiceResponse", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public WindowsFormsApplication4.ServiceSF.sfexpressServiceResponseBody Body;
        
        public sfexpressServiceResponse() {
        }
        
        public sfexpressServiceResponse(WindowsFormsApplication4.ServiceSF.sfexpressServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sfexpressServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sfexpressServiceResponseBody() {
        }
        
        public sfexpressServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class expressServiceForRouteLabel {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="expressServiceForRouteLabel", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelBody Body;
        
        public expressServiceForRouteLabel() {
        }
        
        public expressServiceForRouteLabel(WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class expressServiceForRouteLabelBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public expressServiceForRouteLabelBody() {
        }
        
        public expressServiceForRouteLabelBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class expressServiceForRouteLabelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="expressServiceForRouteLabelResponse", Namespace="http://service.expressservice.integration.sf.com/", Order=0)]
        public WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelResponseBody Body;
        
        public expressServiceForRouteLabelResponse() {
        }
        
        public expressServiceForRouteLabelResponse(WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class expressServiceForRouteLabelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public expressServiceForRouteLabelResponseBody() {
        }
        
        public expressServiceForRouteLabelResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WindowsFormsApplication4.ServiceSF.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WindowsFormsApplication4.ServiceSF.IService>, WindowsFormsApplication4.ServiceSF.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication4.ServiceSF.sfexpressServiceResponse WindowsFormsApplication4.ServiceSF.IService.sfexpressService(WindowsFormsApplication4.ServiceSF.sfexpressService request) {
            return base.Channel.sfexpressService(request);
        }
        
        public string sfexpressService(string arg0) {
            WindowsFormsApplication4.ServiceSF.sfexpressService inValue = new WindowsFormsApplication4.ServiceSF.sfexpressService();
            inValue.Body = new WindowsFormsApplication4.ServiceSF.sfexpressServiceBody();
            inValue.Body.arg0 = arg0;
            WindowsFormsApplication4.ServiceSF.sfexpressServiceResponse retVal = ((WindowsFormsApplication4.ServiceSF.IService)(this)).sfexpressService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication4.ServiceSF.sfexpressServiceResponse> WindowsFormsApplication4.ServiceSF.IService.sfexpressServiceAsync(WindowsFormsApplication4.ServiceSF.sfexpressService request) {
            return base.Channel.sfexpressServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication4.ServiceSF.sfexpressServiceResponse> sfexpressServiceAsync(string arg0) {
            WindowsFormsApplication4.ServiceSF.sfexpressService inValue = new WindowsFormsApplication4.ServiceSF.sfexpressService();
            inValue.Body = new WindowsFormsApplication4.ServiceSF.sfexpressServiceBody();
            inValue.Body.arg0 = arg0;
            return ((WindowsFormsApplication4.ServiceSF.IService)(this)).sfexpressServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelResponse WindowsFormsApplication4.ServiceSF.IService.expressServiceForRouteLabel(WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabel request) {
            return base.Channel.expressServiceForRouteLabel(request);
        }
        
        public string expressServiceForRouteLabel(string arg0) {
            WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabel inValue = new WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabel();
            inValue.Body = new WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelBody();
            inValue.Body.arg0 = arg0;
            WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelResponse retVal = ((WindowsFormsApplication4.ServiceSF.IService)(this)).expressServiceForRouteLabel(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelResponse> WindowsFormsApplication4.ServiceSF.IService.expressServiceForRouteLabelAsync(WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabel request) {
            return base.Channel.expressServiceForRouteLabelAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelResponse> expressServiceForRouteLabelAsync(string arg0) {
            WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabel inValue = new WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabel();
            inValue.Body = new WindowsFormsApplication4.ServiceSF.expressServiceForRouteLabelBody();
            inValue.Body.arg0 = arg0;
            return ((WindowsFormsApplication4.ServiceSF.IService)(this)).expressServiceForRouteLabelAsync(inValue);
        }
    }
}
